---
grails:
    profile: web
    codegen:
        defaultPackage: deliciousorders
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

# dataSource:
#     pooled: true
#     jmxExport: true
#     driverClassName: org.h2.Driver
#     username: sa
#     password: ''

#-# conexión a BBDD Oracle #-#
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: 'oracle.jdbc.OracleDriver'
    dialect: 'org.hibernate.dialect.Oracle10gDialect'
    dbCreate: none
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

environments:
#NOTA: SIEMPRE establecer dbCreate: none, en caso de no querer actualizar el modelo
#de lo contrario es posible que un plugin o alguna configuracion establezca un "create" o "create-drop"
#y elimine filas de las tablas de la base de datos.
   
    development:
        dataSource:
            dbCreate: create
            url: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)))'
            username: 'ruben'
            password: 'kbxcanf2lvobfx'
            logSql: true
            formatSql: true
            properties:
            jmxEnabled : true
            initialSize : 5
            maxActive : 50
            minIdle : 5
            maxIdle : 25
            maxWait : 10000
            maxAge : 600000
            timeBetweenEvictionRunsMillis : 5000
            minEvictableIdleTimeMillis : 60000
            validationQuery : "SELECT 1 from dual"
            validationQueryTimeout : 3
            validationInterval : 15000
            testOnBorrow : true
            testWhileIdle : true
            testOnReturn : false
        test:
            dataSource:
                dbCreate: none       
                url: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)))'
        production:
            dataSource:
                dbCreate: none       
                url: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(HOST=localhost)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)))'